# Generated by Django 5.2.4 on 2025-07-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='List of visible fields for employees in this org'),
        ),
    ]
